### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by tballmsft** [microsoft/microbit-robot#58]
Add robot extension to MakeCode and create this program (https://makecode.microbit.org/_PEqVT5VRaXzb): 
```
robot.setRadioGroup(1)
robot.elecfreaksCuteBot.start()
```
See following error in console:
```
pxtapp.js:1  unhandled exception: Add 'robot start ...' block in the 'on start' block
   at instance (pxt_modules/microbit-robot/robotdriver.ts:47:9)
   at setRadioGroup (pxt_modules/microbit-robot/blocks.ts:256:5)
   at <main> (pxt_modules/ws2812b/main.ts:1:1)
```

**Comment by tballmsft** [comment]
This error doesn't occur when the setRadioGroup statement is removed.
